name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    runs-on: [ self-hosted, linux ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake and Build
        run: ./build.sh

      - name: Test
        run: ./test.sh
