name: Build and Test

on:
  push:
    branches: [ "main", "github_workflow" ]
  pull_request:
    branches: [ "main", "github_workflow" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    runs-on: [ self-hosted, linux ]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout msquic submodule
        run: git submodule update --init

      - name: Configure CMake and Build
        run: ./build.sh

      - name: Test
        run: ./test.sh
#        working-directory: ${{github.workspace}}/build
#        # Execute tests defined by the CMake configuration.
#        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#        run: ctest -C ${{env.BUILD_TYPE}}
