name: Build and Test

on:
  push:
    branches: [ "github_workflow" ]
  pull_request:
    branches: [ "github_workflow" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout msquic submodule
      run: git submodule update --init

    - name: Setup pre-requisites
      run: sudo ./.github/workflows/setup.sh

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      # Execute tests defined by the CMake configuration.
#      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#      run: ctest -C ${{env.BUILD_TYPE}}
